### ISSUE TITLE
missing 6181 nvram for some MXIII-1G variants

### ISSUE THREAD

**Issue by M0Rf30** [dtechsrv/LibreELEC-AML#30] opened 2023-10-02 13:11 UTC
Hi and thanks for your efforts.
Seems that my variant has this nvram descriptor
```
<4>[   27.085041@2] dhd_conf_set_hw_oob_intr: Enable HW OOB for 43362
<4>[   27.091546@2] dhd_conf_set_fw_name_by_chip: firmware_path=/etc/wifi/40181/fw_bcm40181a2.bin
<4>[   27.108065@2] @@@@@nv_6181_path=@@@@@@@
<4>[   27.108133@2] dhd_conf_read_config: nv_path = /etc/wifi/40181/nvram_ap6181.txt
<4>[   27.115589@2] dhd_conf_set_nv_path: nv_path is changed to /etc/wifi/40181/nvram_ap6181.txt
<4>[   27.122934@2] Final fw_path=/etc/wifi/40181/fw_bcm40181a2.bin
<4>[   27.127625@2] Final nv_path=/etc/wifi/40181/nvram_ap6181.txt
<4>[   27.133227@2] Final conf_path=/system/etc/wifi/config.txt
<4>[   27.202977@0] NVRAM version: AP6181_NVRAM_V1.1_01152013
<4>[   27.204101@0] dhdsdio_write_vars: Download, Upload and compare of NVRAM succeeded.
<4>[   27.216794@0] dhd_bus_init: delay 100ms for BCM43362
```
Is it possible to add  it?
Thanks

**Comment by dtechsrv** [comment] 2023-10-02 14:00
What system is generated this kernel log snippet? Would it be possible to request a complete (not truncated) kernel log?

**Comment by M0Rf30** [comment] 2023-10-02 18:47
This is the dmesg generated by LibreELEC-AML
[dmesg.txt](https://github.com/dtechsrv/LibreELEC-AML/files/12785477/dmesg.txt)

This the one generated by stock kernel
https://github.com/M0Rf30/amlogic-s8x2/blob/main/dmesg

**Comment by dtechsrv** [comment] 2023-10-04 13:04
First, try the M8S+ image from an sd card, because it has a bcmdhd driver version that is suitable for several Broadcom wifi chips. Under all other Meson8/8m2 images, the configuration of the Broadcom chip is fixed.

_Unfortunately, I can't go deeper into the MXIII* images because I can't test them. I have already tried several similar modification attempts, but unfortunately the owners indicated that these did not work, so I stopped these modifications, which I cannot test._

**Comment by M0Rf30** [comment] 2023-10-04 13:54
I opened the hardware and the chip is here, marked as ap6181. My supposition is that mxIII 1g doesn't have support for it. maybe adding it would finally load the appropriate nvram? Mine is only an hypothesis

**Comment by dtechsrv** [comment] 2023-10-04 17:38
In the meantime, I realized that the M8S+ image won't boot since there is only 1G of RAM in the box.

The bcmdhd driver in the MXIII* images is not able to "find" the correct hardware id, because it works incorrectly for some reason. Therefore, the hardware id is "hardwired" into the kernel configuration, so it is not possible to modify it afterwards:
https://github.com/dtechsrv/LibreELEC-AML/blob/6e73c2e83460a46df50fe934ed3f87a5c9480436/projects/S8X2/devices/MXIII-1G/linux/linux.arm.conf#L1142

If you want to modify it, you have to compile it from source and test it yourself. Since I don't have such a box, I already indicated that I don't want to modify the original code, because I can't test it, and in addition, I could spoil the functionality of the existing devices. And I want to avoid that...

**Comment by dtechsrv** [comment] 2023-11-14 10:56
I found the cause of the previous errors, so I enabled the updated universal `bcmdhd` driver, but it should be checked.

If there is a compiled image, I will send a link.

**Comment by dtechsrv** [comment] 2023-11-14 18:00
And there it is:
https://libreelec.dtech.hu/snapshots/20231114_s8x2-bcmdhd-v2_66af60b/

If you have the chance, please test it. I hope it works. Thanks.

**Comment by M0Rf30** [comment] 2023-11-14 18:07
I will give confirmations in the next days

**Comment by dtechsrv** [comment] 2023-11-19 09:10
I don't want to rush you, but I'd like to release LE-AML v9.2.8.12 and if that works, that would be included.
And this is the one thing I'm waiting for before release.

**Comment by M0Rf30** [comment] 2023-11-19 11:42
I tested it and works

**Comment by dtechsrv** [comment] 2023-11-19 11:50
Can I get a kernel log?

**Comment by dtechsrv** [comment] 2023-11-21 08:01
I'm closing this now, but regardless, I would have been really happy if you had sent me a log.

**Closed by dtechsrv** 2023-11-21 08:01 UTC
